database:
  mongodb:
    uri: 'mongodb://0.0.0.0:27017'
    database: 'dev'

motd:
  - '&f&m--------------------------------'
  - '&fWelcome, &c%player%'
  - '&aWebsite&f: https://hcfrevival.net/'
  - '&9Discord&f: https://discord.gg/hzk6y66'
  - '&cReddit&f: https://reddit.com/r/hcfrevival'
  - '&6Shop&f: https://shop.hcfrevival.net/'
  - '&f&m--------------------------------'

spawn:
  x: 0.0
  y: 64.0
  z: 0.0
  yaw: 0.0
  pitch: 0.0
  world: 'world'